export const PLANNER_THEME = {
  shellSurface: 'linear-gradient(180deg, var(--surface-raised) 0%, rgba(255, 255, 255, 0.68) 100%)',
  shellSurfacePaper:
    'linear-gradient(135deg, rgba(255, 253, 249, 0.98) 0%, rgba(248, 242, 233, 0.98) 72%, rgba(var(--accent-rgb), 0.06) 100%)',
  shellSurfaceTinted:
    'linear-gradient(135deg, var(--surface-raised) 0%, var(--surface-tint) 58%, rgba(var(--accent-rgb), 0.08) 100%)',
  shellSurfaceWarm:
    'linear-gradient(135deg, var(--surface-raised) 0%, var(--surface-tint) 58%, rgba(var(--accent-warm-rgb), 0.1) 100%)',
  shellBorder: 'var(--shell-border)',
  shellBorderStrong: 'rgba(var(--accent-rgb), 0.16)',
  shellBorderSoftAccent: 'rgba(var(--accent-rgb), 0.12)',
  shellBorderWarm: 'rgba(var(--accent-warm-rgb), 0.18)',
  shellText: 'var(--text-main)',
  shellTextMuted: 'var(--text-muted)',
  shellTextFaint: 'var(--text-faint)',
  shellAccent: 'var(--accent)',
  shellAccentStrong: 'var(--accent-strong)',
  shellWarm: 'var(--accent-warm)',
  shellDanger: 'var(--text-danger)',
  shellShadow: '0 18px 38px rgba(24, 34, 48, 0.08)',
  controlBg: 'var(--bg-surface)',
  controlBgActive: 'var(--bg-subtle)',
  controlBorder: 'var(--border-subtle)',
  controlBorderStrong: 'var(--border-strong)',
  controlText: 'var(--text-main)',
  controlTextMuted: 'var(--text-muted)',
  surface: 'var(--bg-surface)',
  surfaceRaised: 'var(--bg-panel)',
  surfacePanel: 'var(--bg-panel)',
  surfacePanelSoft: 'var(--bg-subtle)',
  surfaceHeader: 'var(--bg-subtle)',
  surfaceHover: 'var(--bg-hover)',
  surfaceInset: 'var(--bg-surface)',
  border: 'var(--border-subtle)',
  borderStrong: 'var(--border-strong)',
  text: 'var(--text-main)',
  textMuted: 'var(--text-muted)',
  textFaint: 'var(--text-faint)',
  success: '#20c38b',
  warning: '#d59222',
  danger: '#cc4747',
  info: '#2f80ed',
  offBg: '#3a3733',
  offBorder: '#5a5550',
  offText: '#d7d1c8',
  absenceBg: '#f5e9d8',
  absenceBorder: '#e7c784',
  absenceText: '#9e6713',
  justifiedBg: '#433425',
  justifiedBorder: '#7a5930',
  justifiedText: '#e0a958',
  vacationBg: '#19353d',
  vacationBorder: '#2b6774',
  vacationText: '#93d9e7',
  licenseBg: '#302445',
  licenseBorder: '#7751b2',
  licenseText: '#d9c1ff',
  holidayBg: '#173126',
  holidayBorder: '#2f6a56',
  holidayText: '#8fdcbc',
  coverageCoveredBg: '#112922',
  coverageCoveredBorder: '#236d58',
  coverageCoveredText: '#87dec0',
  coverageCoveringBg: '#15243c',
  coverageCoveringBorder: '#355f96',
  coverageCoveringText: '#9fc7ff',
  focusRing: 'rgba(47, 128, 237, 0.4)',
} as const
