import type { CSSProperties } from 'react'

export const representativeFormStyles = {
  form: {
    background: 'rgba(255, 255, 255, 0.94)',
    padding: '22px',
    borderRadius: '18px',
    border: '1px solid rgba(148, 163, 184, 0.18)',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    boxShadow: '0 14px 34px rgba(15, 23, 42, 0.04)',
  } satisfies CSSProperties,
  sectionTitle: {
    display: 'block',
    fontSize: '13px',
    fontWeight: 500,
    marginBottom: '6px',
    color: 'var(--text-main)',
  } satisfies CSSProperties,
  input: {
    width: '100%',
    padding: '8px 10px',
    border: '1px solid rgba(148, 163, 184, 0.3)',
    borderRadius: '10px',
    fontSize: '14px',
    boxSizing: 'border-box',
    background: 'rgba(255, 255, 255, 0.96)',
  } satisfies CSSProperties,
  select: {
    width: '100%',
    padding: '8px 10px',
    border: '1px solid rgba(148, 163, 184, 0.3)',
    borderRadius: '10px',
    fontSize: '14px',
    boxSizing: 'border-box',
    background: 'rgba(255, 255, 255, 0.96)',
  } satisfies CSSProperties,
  helperText: {
    fontSize: '12px',
    color: 'var(--text-muted)',
    marginBottom: '8px',
    marginTop: 0,
  } satisfies CSSProperties,
  liveSummary: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
  } satisfies CSSProperties,
  liveSummaryChip: {
    padding: '7px 10px',
    borderRadius: '999px',
    background: 'rgba(248, 250, 252, 0.96)',
    border: '1px solid rgba(148, 163, 184, 0.18)',
    color: '#475569',
    fontSize: '12px',
    fontWeight: 700,
  } satisfies CSSProperties,
  changeNoticeIdle: {
    padding: '14px 16px',
    borderRadius: '14px',
    border: '1px solid rgba(148, 163, 184, 0.18)',
    background: 'rgba(248, 250, 252, 0.92)',
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  } satisfies CSSProperties,
  changeNoticePending: {
    padding: '14px 16px',
    borderRadius: '14px',
    border: '1px solid rgba(124, 58, 237, 0.2)',
    background: 'rgba(245, 243, 255, 0.92)',
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  } satisfies CSSProperties,
  changeNoticeTitle: {
    fontSize: '13px',
    fontWeight: 700,
    color: 'var(--text-main)',
  } satisfies CSSProperties,
  changeNoticeBody: {
    fontSize: '12px',
    lineHeight: 1.6,
    color: 'var(--text-muted)',
  } satisfies CSSProperties,
  footer: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '12px',
    marginTop: '8px',
    flexWrap: 'wrap',
  } satisfies CSSProperties,
  secondaryButton: {
    padding: '8px 14px',
    background: 'white',
    color: '#334155',
    border: '1px solid rgba(148, 163, 184, 0.24)',
    borderRadius: '10px',
    cursor: 'pointer',
    fontWeight: 600,
    fontSize: '14px',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  } satisfies CSSProperties,
  submitButton: {
    padding: '8px 16px',
    background: '#111827',
    color: 'white',
    border: 'none',
    borderRadius: '10px',
    cursor: 'pointer',
    fontWeight: 600,
    fontSize: '14px',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  } satisfies CSSProperties,
  submitButtonDisabled: {
    padding: '8px 16px',
    background: '#cbd5e1',
    color: '#475569',
    border: 'none',
    borderRadius: '10px',
    cursor: 'not-allowed',
    fontWeight: 600,
    fontSize: '14px',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  } satisfies CSSProperties,
} as const
