import type { CSSProperties } from 'react'

export const settingsViewStyles = {
  tab: (isActive: boolean): CSSProperties => ({
    padding: '10px 20px',
    cursor: 'pointer',
    border: 'none',
    borderBottom: isActive
      ? '2px solid hsl(0, 0%, 13%)'
      : '2px solid transparent',
    color: isActive ? '#111827' : '#4b5563',
    fontWeight: isActive ? 600 : 500,
    background: 'transparent',
    fontSize: '15px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  }),
  subTab: (isActive: boolean): CSSProperties => ({
    padding: '8px 16px',
    borderRadius: '999px',
    border: '1px solid',
    borderColor: isActive ? 'rgba(37, 99, 235, 0.16)' : 'transparent',
    background: isActive ? 'white' : 'transparent',
    color: isActive ? '#1d4ed8' : '#64748b',
    fontSize: '13px',
    fontWeight: 700,
    cursor: 'pointer',
    transition: 'all 0.2s',
    boxShadow: isActive ? '0 8px 18px rgba(37, 99, 235, 0.08)' : 'none',
  }),
  settingItem: {
    background: 'var(--bg-panel)',
    border: '1px solid var(--border-subtle)',
    borderRadius: '12px',
    padding: '20px',
    marginBottom: '16px',
    boxShadow: '0 1px 2px rgba(0,0,0,0.05)',
  } satisfies CSSProperties,
  button: {
    padding: '8px 16px',
    borderRadius: '6px',
    border: '1px solid #e5e7eb',
    background: '#fff',
    color: '#374151',
    fontSize: '14px',
    fontWeight: 500,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  } satisfies CSSProperties,
  dangerButton: {
    padding: '8px 16px',
    borderRadius: '6px',
    border: '1px solid #fecaca',
    background: '#fef2f2',
    color: '#991b1b',
    fontSize: '14px',
    fontWeight: 500,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  } satisfies CSSProperties,
}
