import type { CSSProperties } from 'react'

export const settingsViewStyles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    padding: '0 20px 40px',
    width: 'min(1680px, calc(100% - 32px))',
    maxWidth: '1680px',
    margin: '0 auto 40px',
  } satisfies CSSProperties,
  hero: {
    borderRadius: '22px',
    border: '1px solid var(--shell-border)',
    background:
      'linear-gradient(180deg, rgba(255,255,255,0.88) 0%, rgba(248,242,233,0.42) 100%)',
    boxShadow: 'var(--shadow-sm)',
    padding: '14px 16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
    flexWrap: 'wrap',
    overflow: 'hidden',
  } satisfies CSSProperties,
  heroCopy: {
    display: 'grid',
    gap: '2px',
    minWidth: 0,
  } satisfies CSSProperties,
  heroTitle: {
    margin: 0,
    fontSize: '1.45rem',
    lineHeight: 1.05,
    color: 'var(--text-main)',
    letterSpacing: '-0.03em',
  } satisfies CSSProperties,
  heroContext: {
    margin: 0,
    color: 'var(--text-muted)',
    fontSize: '13px',
    lineHeight: 1.45,
    fontWeight: 500,
  } satisfies CSSProperties,
  tabRail: {
    display: 'inline-flex',
    gap: '6px',
    flexWrap: 'wrap',
    padding: '4px',
    borderRadius: '18px',
    border: '1px solid var(--shell-border)',
    background: 'var(--surface-tint)',
    width: 'fit-content',
    boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.55)',
  } satisfies CSSProperties,
  tab: (isActive: boolean): CSSProperties => ({
    padding: '9px 13px',
    cursor: 'pointer',
    border: `1px solid ${isActive ? 'rgba(var(--accent-rgb), 0.18)' : 'transparent'}`,
    color: isActive ? 'var(--accent-strong)' : 'var(--text-muted)',
    fontWeight: isActive ? 700 : 600,
    background: isActive
      ? 'linear-gradient(180deg, var(--surface-raised) 0%, rgba(255,255,255,0.68) 100%)'
      : 'transparent',
    fontSize: '13px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    borderRadius: '14px',
    boxShadow: isActive ? '0 10px 18px rgba(var(--accent-rgb), 0.08)' : 'none',
    transition: 'all 0.2s ease',
  }),
  subTab: (isActive: boolean): CSSProperties => ({
    padding: '9px 14px',
    borderRadius: '999px',
    border: '1px solid',
    borderColor: isActive ? 'rgba(var(--accent-rgb), 0.18)' : 'rgba(95, 109, 125, 0.12)',
    background: isActive
      ? 'linear-gradient(180deg, var(--surface-raised) 0%, rgba(255,255,255,0.7) 100%)'
      : 'transparent',
    color: isActive ? 'var(--accent-strong)' : 'var(--text-muted)',
    fontSize: '13px',
    fontWeight: 700,
    cursor: 'pointer',
    transition: 'all 0.2s',
    boxShadow: isActive ? '0 10px 18px rgba(var(--accent-rgb), 0.1)' : 'none',
  }),
  contentSurface: {
    background: 'linear-gradient(180deg, var(--surface-raised) 0%, var(--bg-panel) 100%)',
    borderRadius: '26px',
    border: '1px solid var(--shell-border)',
    padding: '24px',
    minHeight: '600px',
    boxShadow: 'var(--shadow-sm)',
  } satisfies CSSProperties,
  settingItem: {
    background: 'linear-gradient(180deg, var(--surface-raised) 0%, var(--bg-panel) 100%)',
    border: '1px solid var(--shell-border)',
    borderRadius: '22px',
    padding: '22px',
    marginBottom: '16px',
    boxShadow: 'var(--shadow-sm)',
  } satisfies CSSProperties,
  sectionEyebrow: {
    margin: '0 0 6px',
    fontSize: '11px',
    fontWeight: 800,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: 'var(--accent)',
  } satisfies CSSProperties,
  sectionTitle: {
    margin: '0 0 4px 0',
    fontSize: '18px',
    color: 'var(--text-main)',
    letterSpacing: '-0.02em',
  } satisfies CSSProperties,
  sectionDescription: {
    margin: 0,
    fontSize: '13px',
    color: 'var(--text-muted)',
    lineHeight: 1.65,
  } satisfies CSSProperties,
  button: {
    padding: '10px 15px',
    borderRadius: '16px',
    border: '1px solid var(--shell-border)',
    background: 'linear-gradient(180deg, var(--surface-raised) 0%, var(--surface-veil) 100%)',
    color: 'var(--text-main)',
    fontSize: '14px',
    fontWeight: 700,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    boxShadow: 'var(--shadow-sm)',
  } satisfies CSSProperties,
  dangerButton: {
    padding: '10px 15px',
    borderRadius: '16px',
    border: '1px solid var(--border-danger)',
    background: 'linear-gradient(180deg, var(--bg-danger) 0%, rgba(255,255,255,0.5) 100%)',
    color: 'var(--text-danger)',
    fontSize: '14px',
    fontWeight: 700,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    boxShadow: 'var(--shadow-sm)',
  } satisfies CSSProperties,
  toggleButton: (isActive: boolean): CSSProperties => ({
    padding: '10px 16px',
    borderRadius: '999px',
    border: `1px solid ${isActive ? 'rgba(var(--accent-rgb), 0.2)' : 'var(--border-subtle)'}`,
    background: isActive
      ? 'linear-gradient(180deg, var(--accent) 0%, var(--accent-strong) 100%)'
      : 'linear-gradient(180deg, var(--bg-subtle) 0%, var(--surface-veil) 100%)',
    color: isActive ? 'var(--text-on-accent)' : 'var(--text-main)',
    fontSize: '13px',
    fontWeight: 700,
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    boxShadow: isActive ? '0 16px 28px rgba(var(--accent-rgb), 0.18)' : 'none',
  }),
}
